spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQLDB_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
      platform: mysql

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: API Document
    version: v1.0.0
    description: Spring Boot API Document by HauHH
    server:
      url: http://localhost:${server.port}
      description: Spring Boot

com:
  hauhh:
    key: ${KEY_TEST}
    valid-duration: ${KEY_DURATION_TEST} # in seconds
    refreshable-duration: ${KEY_REFRESHABLE_DURATION_TEST}