server:
  port: ${SPRING_PORT}
spring:
  application:
    name: SpringBoot
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


com:
  hauhh:
    key: "GMOetuUdwobZblQf2oCvbOuUT3jIEO05KdZ1RgFxGE1rDglmti25nVNLrNF6eCtY"
    valid-duration: 3600 # in seconds
    refreshable-duration: 36000 #in second

